# Generated by Django 5.1 on 2024-08-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='description',
            field=models.CharField(max_length=550),
        ),
    ]
