# Generated by Django 5.1 on 2024-08-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_alter_prueba_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='genre',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='prueba',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
